# Generated by Django 5.1 on 2024-09-18 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DatePaiement', models.DateField()),
                ('MoisCotisation', models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], max_length=100)),
                ('AnneeConcernee', models.IntegerField()),
                ('MontantCotise', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherent.adherent')),
            ],
        ),
    ]
