# Generated by Django 5.1 on 2024-09-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeAdh', models.CharField(blank=True, max_length=20, unique=True)),
                ('NomAdh', models.CharField(max_length=100)),
                ('PrenomAdh', models.CharField(max_length=100)),
                ('SexeAdh', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('DateAdhesionAdh', models.DateField()),
                ('TelephoneAdh', models.CharField(max_length=20, unique=True)),
                ('EmailAdh', models.EmailField(blank=True, max_length=100, null=True)),
                ('AdresseAdh', models.TextField()),
                ('MontantACotiserAdh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StatutAdh', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('Suspendu', 'Suspendu')], max_length=20)),
                ('ImageAdh', models.ImageField(blank=True, null=True, upload_to='adherents/')),
            ],
        ),
    ]
